export const ADD_POST = 'ADD_POST'
export const LIKE_POST = 'LIKE_POST'
export const GET_POSTS = 'GET_POSTS'
export const SINGLE_POST = 'SINGLE_POST'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const DELETE_POST = 'DELETE_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
// export const ADD_POST = 'ADD_POST'